coverage:
  precision: 2
  round: nearest
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 15%
    patch:
      default:
        target: auto
        threshold: 15%
