version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        - '*'
      dependencies:
        - '*'
    labels:
      - "dependencies"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    labels:
      - "dependencies"
    allow:
      - dependency-type: "direct"
