run:
  timeout: 15s
  modules-download-mode: readonly

  # Include test files or not. Default: true
  tests: true

  allow-parallel-runners: true
  concurrency: 8

linters:
  disable-all: true
  fast: true
  enable:
    - gocyclo
    - govet
    - maintidx
    - misspell
    - unused
    - unparam

severity:
  default-severity: warning
  case-sensitive: false

linters-settings:
  gocyclo:
    min-complexity: 30

  funlen:
    lines: 100
    statements: 80

  gocritic:
    disabled-checks:
      - exitAfterDefer

  gosec:
    severity: medium
    config:
      G301: "0755" # Maximum allowed permissions mode for os.Mkdir and os.MkdirAll - Default: "0750"
      G302: "0644" # Maximum allowed permissions mode for os.OpenFile and os.Chmod - Default: "0600"
      G306: "0644" # Maximum allowed permissions mode for os.WriteFile and ioutil.WriteFile - Default: "0600"

  maintidx:
    under: 25

  misspell:
    locale: US

  nestif:
    min-complexity: 4 # Minimal complexity of if statements to report. - Default: 5
