env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - task update-version-file

universal_binaries:
  - replace: false

archives:
  - format_overrides:
      - goos: windows
        format: zip

builds:
  - main: ./cmd/stack-supervisor
    binary: 'stack-supervisor'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

brews:
  -
    name: 'stack-supervisor'
    homepage: 'https://github.com/permafrost-dev/stack-supervisor'
    description: 'a single application to manage your entire dev stack'
    license: "MIT"
    tap:
      owner: 'permafrost-dev'
      name: homebrew-stack-supervisor
      branch: main

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
