env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - task mod
    - task update-version-file

universal_binaries:
  - replace: false

archives:
  - format: zip

builds:
  - id: stackup
    main: ./app
    binary: stackup
    mod_timestamp: '{{ .CommitTimestamp }}'
    no_unique_dist_dir: true
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

# brews:
#   -
#     name: stackup
#     homepage: 'https://github.com/stackup-app/homebrew-stackup'
#     description: 'a single application to manage your entire dev stack'
#     download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
#     custom_require: "lib/custom_download_strategy"
#     license: MIT
#     repository:
#       owner: stackup-app
#       name: homebrew-stackup
#       branch: main

checksum:
  name_template: checksums.txt
  algorithm: sha256
