# This file can be run with the `task` utility: https://taskfile.dev/
version: '3'

vars:
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  VERSION:
    sh: go run tools/build-version.go

tasks:

  mod:
    desc: Downloads and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy

  build:
    cmds:
      - task: build-stack-supervisor

  clean:
    desc: Cleans up build artifacts
    cmds:
      - rm -f ./dist/stack-supervisor
    status:
      - test -f ./dist/stack-supervisor

  lint:
    cmds:
      - task: lint-stack-supervisor

  update-version-file:
    cmds:
      - printf "package main\n\nvar Version = \"{{.VERSION}}\"" > ./cmd/stack-supervisor/version.go
    status:
      - test -f ./cmd/stack-supervisor/version.go
      - grep -q "\"{{.VERSION}}\"" ./cmd/stack-supervisor/version.go

  lint-stack-supervisor:
    desc: Runs golangci-lint
    cmds:
      - golangci-lint run ./cmd/**

  build-stack-supervisor:
    desc: Builds stack-supervisor binary
    deps:
      - task: update-version-file
    sources:
      - './cmd/stack-supervisor/**/*.go'
    generates:
      - ./dist/stack-supervisor
    cmds:
      - mkdir -p ./dist
      - go build -trimpath -ldflags="-s -w -X main.Version={{.VERSION}}-{{.GIT_COMMIT}}" -o dist ./cmd/stack-supervisor
