name: example shared configuration settings
version: 1.0.0
last-modified: 2023-Aug-04 19:11
author: Patrick Organ <patrick@permafrost.dev>
description: example of shared configuration settings

settings:
  anonymous-stats: true
  domains:
    allowed:
      - '*.githubusercontent.com'
      - api.github.com
      - app.posthog.com

init:
preconditions:
tasks:
