name: build
on:
  push:
  pull_request:
  pull_request_target:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: "~1.20"
      GO111MODULE: "on"

    steps:

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: $GO_VERSION
          cache-dependency-path: ./go.sum

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Go modules
        run: go mod download

      - name: Build Application
        id: build
        run: task build

      - name: Run Tests with Coverage
        if: ${{success()}}
        run: go test -cover -coverprofile=coverage.out -covermode=atomic -v ./.../lib/**

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
